"""Pydantic schemas."""
from app.schemas.code import (
    CodeArtifactCreate,
    CodeArtifactResponse,
    CodeArtifactUpdate,
    CodeExportRequest,
    CodeExportResponse,
    CodeFile,
    CodeGenerationRequest,
    CodeValidationRequest,
    LintResult,
    TestResult,
    ValidationResult,
)
from app.schemas.common import (
    BaseSchema,
    ErrorResponse,
    MessageResponse,
    PaginatedResponse,
    StatusResponse,
    TimestampMixin,
)
from app.schemas.epic import (
    EpicApproval,
    EpicCreate,
    EpicGenerationRequest,
    EpicResponse,
    EpicUpdate,
    EpicWithStoriesResponse,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectResponse,
    ProjectUpdate,
    ProjectWithRunsResponse,
    ResearchArtifactResponse,
    RunCreate,
    RunDetailResponse,
    RunResponse,
    TraceabilityMatrixResponse,
)
from app.schemas.spec import (
    APIEndpoint,
    DataModel,
    DataModelField,
    SecurityRequirement,
    SpecApproval,
    SpecCreate,
    SpecGenerationRequest,
    SpecResponse,
    SpecUpdate,
    SpecWithCodeResponse,
    TestCase,
)
from app.schemas.story import (
    AcceptanceCriterion,
    StoryApproval,
    StoryCreate,
    StoryGenerationRequest,
    StoryResponse,
    StoryUpdate,
    StoryWithSpecsResponse,
)
from app.schemas.user import (
    Token,
    TokenPayload,
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
    UserWithProjectCount,
)

__all__ = [
    # Common
    "BaseSchema",
    "TimestampMixin",
    "PaginatedResponse",
    "MessageResponse",
    "ErrorResponse",
    "StatusResponse",
    # User
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "UserWithProjectCount",
    "Token",
    "TokenPayload",
    # Project
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectWithRunsResponse",
    "RunCreate",
    "RunResponse",
    "RunDetailResponse",
    "ResearchArtifactResponse",
    "TraceabilityMatrixResponse",
    # Epic
    "EpicCreate",
    "EpicUpdate",
    "EpicApproval",
    "EpicResponse",
    "EpicWithStoriesResponse",
    "EpicGenerationRequest",
    # Story
    "AcceptanceCriterion",
    "StoryCreate",
    "StoryUpdate",
    "StoryApproval",
    "StoryResponse",
    "StoryWithSpecsResponse",
    "StoryGenerationRequest",
    # Spec
    "APIEndpoint",
    "DataModel",
    "DataModelField",
    "SecurityRequirement",
    "TestCase",
    "SpecCreate",
    "SpecUpdate",
    "SpecApproval",
    "SpecResponse",
    "SpecWithCodeResponse",
    "SpecGenerationRequest",
    # Code
    "CodeFile",
    "ValidationResult",
    "LintResult",
    "TestResult",
    "CodeArtifactCreate",
    "CodeArtifactUpdate",
    "CodeArtifactResponse",
    "CodeGenerationRequest",
    "CodeValidationRequest",
    "CodeExportRequest",
    "CodeExportResponse",
]
